import { normalizeProfileAddress } from '../../library/config.js';
import { resolveContentUrl } from '../../library/data/resolveContentUrl.js';

export const PROFILE_IDENTITY_STATUS = Object.freeze({ IDLE: 'IDLE', LOADING: 'LOADING', RESOLVED: 'RESOLVED', UNAVAILABLE: 'UNAVAILABLE', ERROR: 'ERROR' });
const cleanText = (value, maxLength) => { if (typeof value !== 'string') return null; const clean = value.replace(/[\u0000-\u001f\u007f-\u009f]/gu, ' ').replace(/\s+/gu, ' ').trim(); return clean ? clean.slice(0, maxLength) : null; };
export function createProfileIdentity(address, overrides = {}) { const normalizedAddress = normalizeProfileAddress(address); if (!normalizedAddress) throw new TypeError('A valid address is required'); return { address: normalizedAddress, normalizedAddress, name: null, avatarUrl: null, description: null, isUniversalProfile: false, status: PROFILE_IDENTITY_STATUS.IDLE, source: overrides.source || 'LIVE', errorCode: null, ...overrides, address: normalizedAddress, normalizedAddress }; }
export function selectProfileAvatar(images, options = {}) { const candidates = (Array.isArray(images) ? images : []).map((image) => ({ url: resolveContentUrl(image?.url || image?.src, options), width: Number(image?.width) || 0 })).filter((image) => image.url).sort((a, b) => a.width - b.width); return candidates.length ? (candidates.find((image) => image.width >= 64) || candidates.at(-1)).url : null; }
export function normalizeLsp3Identity(address, profile, options = {}) { const normalizedAddress = normalizeProfileAddress(address); if (!normalizedAddress || !profile || typeof profile !== 'object') return null; return createProfileIdentity(normalizedAddress, { name: cleanText(profile.name, 80), description: cleanText(profile.description, 280), avatarUrl: selectProfileAvatar(profile.profileImage, options), isUniversalProfile: true, status: PROFILE_IDENTITY_STATUS.RESOLVED, source: options.source || 'LIVE' }); }
export function createUnavailableIdentity(address, { source = 'LIVE', errorCode = 'METADATA_UNAVAILABLE', isUniversalProfile = false } = {}) { return createProfileIdentity(address, { status: PROFILE_IDENTITY_STATUS.UNAVAILABLE, source, errorCode, isUniversalProfile }); }
export function createErrorIdentity(address, { source = 'LIVE', errorCode = 'NETWORK_ERROR' } = {}) { return createProfileIdentity(address, { status: PROFILE_IDENTITY_STATUS.ERROR, source, errorCode }); }
export function getOfficialProfileUrl(address) { const normalized = normalizeProfileAddress(address); return normalized ? `https://universaleverything.io/${normalized}` : null; }
