function ToggleRow({ checked, label, onChange }) {
  return <label className="lattice-window-toggle"><span>{label}</span><input checked={checked} onChange={(event) => onChange(event.target.checked)} type="checkbox" /></label>;
}

export default function LatticeToolbarWindowContent({ commands, data, windowId }) {
  if (windowId === 'theme') return <div className="lattice-window-controls">
    <section><small>PUBLIC PRESENTATION</small><label><span>SURFACE</span><select onChange={(event) => commands.setSurface(event.target.value)} value={data.surfaceId}>{data.surfaces.map(({ id, label }) => <option key={id} value={id}>{label}</option>)}</select></label><label><span>MENU SURFACE</span><select onChange={(event) => commands.setMenuSurface(event.target.value)} value={data.menuSurfaceId}>{data.surfaces.map(({ id, label }) => <option key={id} value={id}>{label}</option>)}</select></label><label><span>OVERLAY INK</span><select onChange={(event) => commands.setOverlayInkSurface(event.target.value)} value={data.overlayInkSurfaceId}><option value="auto">AUTO / MENU CONTRAST</option>{data.surfaces.map(({ id, label }) => <option key={id} value={id}>{label}</option>)}</select></label><ToggleRow checked={data.gridVisible} label="GRID VISIBLE" onChange={commands.setGridVisible} /></section>
    <p>SESSION PREVIEW ONLY / NOT PERSISTED</p>
  </div>;
  if (windowId === 'publish') return <div className="lattice-window-record"><small>PUBLICATION READINESS</small><strong>UNRESOLVED DRAFT</strong><dl><div><dt>PUBLIC DOCUMENT</dt><dd>NOT CONNECTED</dd></div><div><dt>STORAGE</dt><dd>NOT CONNECTED</dd></div><div><dt>WALLET</dt><dd>NOT REQUESTED</dd></div></dl><button disabled type="button">PUBLISH UNAVAILABLE IN FIXTURE</button></div>;
  if (windowId === 'settings') return <div className="lattice-window-record"><small>APPLICATION / PROFILE / KEEPER</small><strong>ADAPTERS UNRESOLVED</strong><dl><div><dt>PROFILE PRESENTATION</dt><dd>FUTURE ADAPTER</dd></div><div><dt>KEEPER PREFERENCES</dt><dd>FUTURE ADAPTER</dd></div><div><dt>APPLICATION</dt><dd>FUTURE ADAPTER</dd></div></dl></div>;
  return <div className="lattice-window-controls"><section><small>PRIVATE EDITOR ERGONOMICS</small><ToggleRow checked={data.reducedMotion} label="REDUCED MOTION" onChange={commands.setReducedMotion} /><ToggleRow checked={data.smartGuides} label="SMART GUIDES" onChange={commands.setSmartGuides} /><ToggleRow checked={data.gridSnap} label="GRID SNAP" onChange={commands.setGridSnap} /><label><span>INTERFACE DENSITY</span><select onChange={(event) => commands.setDensity(event.target.value)} value={data.density}><option value="comfortable">COMFORTABLE</option><option value="compact">COMPACT</option></select></label></section><p>PRIVATE SESSION PREFERENCE / NOT PUBLIC THEME</p></div>;
}
