import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
const origin = process.env.INSCAPE_TEST_ORIGIN || 'http://127.0.0.1:5173';
const browser = await chromium.launch({ executablePath: process.env.INSCAPE_BROWSER || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = []; page.on('pageerror', error => { errors.push(error.message); console.error(error.stack); });
  await page.route('https://raw.githubusercontent.com/**', route => route.fulfill({ path: `public/${new URL(route.request().url()).pathname.split('/public/')[1]}` }));
  await page.route(`${origin}/__mobile__`, route => route.fulfill({ contentType: 'text/html', body: '<div id="root"></div>' }));
  await page.goto(`${origin}/__mobile__`);
  await page.evaluate(async () => {
    const refresh = (await import('/@react-refresh')).default;
    refresh.injectIntoGlobalHook(window); window.$RefreshReg$ = () => {}; window.$RefreshSig$ = () => type => type; window.__vite_plugin_react_preamble_installed__ = true;
    const React = (await import('/@id/react')).default;
    const { createRoot } = (await import('/@id/react-dom/client')).default;
    const Runtime = (await import('/src/public/ownerSystemWorkflow/OwnerSystemWorkflowRuntime.jsx')).default;
    await import('/src/index.css');
    await import('/src/public/ownerSystemWorkflow/ownerSystemWorkflow.css');
    await import('/src/lattice/rendering/latticeMenuSurface.css');
    const fixture = await import('/src/public/ownerSystemWorkflow/ownerSystemWorkflowDevelopmentFixture.js');
    const { systemWorkflowDraftKey } = await import('/src/systemWorkflow/systemWorkflowDraftStore.js');
    const storage = fixture.createOwnerSystemWorkflowReviewStorage();
    const root = createRoot(document.getElementById('root'));
    const props = { profileAddress: fixture.OWNER_SYSTEM_WORKFLOW_REVIEW_PROFILE, reviewStorage: storage,
      reviewAssets: fixture.OWNER_SYSTEM_WORKFLOW_REVIEW_ASSETS, reviewCategories: [], reviewActivity: [], reviewDiscovery: [], reviewProfile: { name: 'residentzero' } };
    const initial = JSON.parse(storage.getItem(systemWorkflowDraftKey(props.profileAddress)));
    initial.identityPresentation.alias = 'Human Underneath'; storage.setItem(systemWorkflowDraftKey(props.profileAddress), JSON.stringify(initial));
    window.review = { root, storage, props, fixture, render: () => root.render(React.createElement(Runtime, props)),
      draft: () => JSON.parse(storage.getItem(systemWorkflowDraftKey(props.profileAddress))) };
    review.render();
  });
  await page.locator('.system-workflow').waitFor();
  await page.screenshot({ path: '.browser-test-runtime/mobile-before-menu.png' });
  await page.locator('.system-workflow').dispatchEvent('contextmenu', { clientX: 15, clientY: 15, bubbles: true });
  await page.getByRole('menuitem', { name: 'ADD', exact: true }).hover();
  await page.getByRole('menuitem', { name: 'MOBILE MODULE', exact: true }).click();
  await page.locator('.mobile-editor-preview').waitFor();
  assert.equal(await page.evaluate(() => review.draft().mobile.visibility), 'PRIVATE');
  assert.equal(await page.locator('.mobile-editor-host .system-workflow__instrument-window').count(), 2);
  await page.locator('.mobile-front-name').filter({ hasText: 'residentzero' }).waitFor();
  const header = await page.getByLabel('Move Mobile window', { exact: true }).boundingBox();
  await page.mouse.move(header.x + 100, header.y + 15); await page.mouse.down();
  await page.mouse.move(header.x + 900, header.y + 15, { steps: 10 }); await page.mouse.up();
  await page.getByRole('button', { name: 'Library', exact: true }).click();
  const source = await page.getByRole('button', { name: 'ABYSSAL STUDY / INSCAPE STUDIES', exact: true }).boundingBox();
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2); await page.mouse.down();
  await page.mouse.move(source.x + source.width / 2 + 20, source.y + source.height / 2, { steps: 3 });
  const target = page.locator('[data-mobile-drop="artwork"]'); await target.waitFor();
  const destination = await target.boundingBox();
  await page.mouse.move(destination.x + destination.width / 2, destination.y + destination.height / 2, { steps: 20 }); await page.mouse.up();
  await page.waitForFunction(() => review.draft().mobile.front.artwork !== null);
  await page.getByRole('button', { name: 'Library', exact: true }).click();
  const movedHeader = await page.getByLabel('Move Mobile window', { exact: true }).boundingBox();
  await page.mouse.move(movedHeader.x + 100, movedHeader.y + 15); await page.mouse.down();
  await page.mouse.move(header.x + 100, header.y + 15, { steps: 10 }); await page.mouse.up();
  const tools = page.locator('.mobile-editor-controls');
  await tools.getByRole('button', { name: 'Rotate', exact: true }).click();
  assert.equal(await page.evaluate(() => review.draft().mobile.front.transforms.artwork.quarterTurns), 1);
  await page.keyboard.press('Control+z');
  assert.equal(await page.evaluate(() => review.draft().mobile.front.transforms?.artwork.quarterTurns || 0), 0);
  await page.keyboard.press('Control+Shift+z');
  assert.equal(await page.evaluate(() => review.draft().mobile.front.transforms.artwork.quarterTurns), 1);
  const scaleHandle = await page.getByRole('button', { name: 'Scale artwork', exact: true }).boundingBox();
  await page.mouse.move(scaleHandle.x + 15, scaleHandle.y + 15); await page.mouse.down();
  await page.mouse.move(scaleHandle.x + 35, scaleHandle.y + 35, { steps: 5 });
  assert.equal(await page.evaluate(() => review.draft().mobile.front.image.scale), 1);
  await page.mouse.up(); assert.ok(await page.evaluate(() => review.draft().mobile.front.image.scale) > 1);
  await page.keyboard.press('Control+z'); assert.equal(await page.evaluate(() => review.draft().mobile.front.image.scale), 1);
  const initialPosition = await page.evaluate(() => review.draft().mobile.front.positions.name);
  const name = await page.locator('.mobile-front-name').boundingBox();
  await page.mouse.move(name.x + name.width / 2, name.y + name.height / 2); await page.mouse.down();
  await page.mouse.move(name.x + name.width / 2 + 35, name.y + name.height / 2 - 25, { steps: 4 });
  assert.deepEqual(await page.evaluate(() => review.draft().mobile.front.positions.name), initialPosition);
  await page.mouse.up();
  const finalPosition = await page.evaluate(() => review.draft().mobile.front.positions.name);
  assert.notDeepEqual(finalPosition, initialPosition);
  assert.ok(Math.abs(finalPosition.x * 1080 / 12 - Math.round(finalPosition.x * 1080 / 12)) < .0001);
  await page.keyboard.press('Control+z'); assert.deepEqual(await page.evaluate(() => review.draft().mobile.front.positions.name), initialPosition);
  await page.keyboard.press('Control+y'); assert.deepEqual(await page.evaluate(() => review.draft().mobile.front.positions.name), finalPosition);
  await page.getByRole('button', { name: 'Close Mobile tools' }).click();
  assert.equal(await page.locator('.mobile-editor-preview').count(), 1);
  await page.getByRole('button', { name: 'Open Mobile tools' }).click();
  await page.locator('.mobile-output-toolbar').getByRole('button', { name: 'Profile', exact: true }).click();
  await page.locator('.mobile-back h2').filter({ hasText: 'residentzero' }).waitFor();
  assert.equal(await page.locator('.mobile-back .mobile-profile-title').textContent(), 'Human Underneath');
  await page.screenshot({ path: '.browser-test-runtime/mobile-profile-hierarchy.png' });
  await page.locator('.mobile-output-toolbar').getByRole('button', { name: 'Works', exact: true }).click();
  await page.getByLabel('Heading', { exact: true }).fill('Chosen works');
  await page.getByLabel('Heading', { exact: true }).press('Enter');
  await page.getByLabel('Heading', { exact: true }).click();
  await page.getByLabel('Heading', { exact: true }).press('End');
  await page.getByLabel('Heading', { exact: true }).pressSequentially(' extra');
  await page.keyboard.press('Control+z');
  assert.equal(await page.evaluate(() => review.draft().mobile.index.title), 'Chosen works', 'Text undo must not undo the profile draft');
  await page.getByLabel('Heading', { exact: true }).press('Escape');
  await page.getByLabel('Heading', { exact: true }).press('Tab');
  const drop = () => page.locator('[data-mobile-drop="index"]').evaluate(node => {
    const dataTransfer = new DataTransfer(); dataTransfer.setData('application/x-inscape-asset', review.fixture.OWNER_SYSTEM_WORKFLOW_REVIEW_ASSETS[0].id);
    node.dispatchEvent(new DragEvent('drop', { dataTransfer, bubbles: true }));
  });
  await drop(); await drop();
  const before = await page.evaluate(() => review.draft().mobile.index.entries.map(e => e.id));
  await page.locator('.mobile-index-item').last().click();
  await tools.getByRole('button', { name: 'Move selected work earlier' }).click();
  assert.deepEqual(await page.evaluate(() => review.draft().mobile.index.entries.map(e => e.id)), before.reverse());
  await page.keyboard.press('Control+z');
  assert.deepEqual(await page.evaluate(() => review.draft().mobile.index.entries.map(e => e.id)), before.reverse());
  const dragOrder = await page.evaluate(() => review.draft().mobile.index.entries.map(e => e.id));
  await page.locator('.mobile-index-item').first().dragTo(page.locator('.mobile-index-item').last());
  assert.deepEqual(await page.evaluate(() => review.draft().mobile.index.entries.map(e => e.id)), dragOrder.reverse());
  await page.keyboard.press('Control+z');
  await page.getByLabel('Include Mobile in next publication').check();
  await page.keyboard.press('Control+z'); assert.equal(await page.evaluate(() => review.draft().mobile.visibility), 'PRIVATE');
  await page.keyboard.press('Control+y'); assert.equal(await page.evaluate(() => review.draft().mobile.visibility), 'PUBLIC');
  await tools.evaluate(node => { node.closest('.system-workflow__instrument-content').scrollTop = 0; });
  await page.screenshot({ path: '.browser-test-runtime/mobile-owner-direct.png' });
  await page.locator('.mobile-output-toolbar').getByRole('button', { name: 'Front', exact: true }).click();
  await page.getByRole('button', { name: 'Close Mobile tools' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  const windowBounds = await page.locator('.mobile-editor-host .system-workflow__instrument-window').boundingBox();
  assert.ok(windowBounds.x >= 0 && windowBounds.x + windowBounds.width <= 390);
  await page.screenshot({ path: '.browser-test-runtime/mobile-editor-narrow.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Open Mobile tools' }).click();
  await page.getByRole('button', { name: 'Close Mobile editor' }).click();
  await page.getByRole('button', { name: 'MOBILE', exact: true }).click();
  assert.equal(await page.evaluate(() => review.draft().mobile.index.title), 'Chosen works');
  const document = await page.evaluate(async () => {
    const { buildProfileDocumentV9 } = await import('/src/profileDocument/domain/profileDocumentV9Builder.js');
    return buildProfileDocumentV9({ profileAddress: review.props.profileAddress, systemWorkflowDraft: review.draft(), assetRecords: review.fixture.OWNER_SYSTEM_WORKFLOW_REVIEW_ASSETS });
  });
  await page.evaluate(async document => {
    const React = (await import('/@id/react')).default, Presentation = (await import('/src/mobile/MobilePresentation.jsx')).default;
    review.root.render(React.createElement('div', { style: { width: '100vw', height: '100vh' } }, React.createElement(Presentation, {
      content: document.mobile, identity: { officialProfile: { name: 'residentzero' }, authoredProfile: { title: 'Human Underneath' }, profile: { description: 'Existing profile information' } } })));
  }, document);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Toggle colour theme' }).click();
  await page.getByRole('button', { name: 'Turn card to profile' }).click();
  await page.locator('.mobile-index-link').click();
  assert.equal(await page.locator('.mobile-index footer').count(), 0);
  await page.locator('.mobile-index-item').first().click();
  assert.equal(await page.locator('.mobile-theme-light').count(), 1);
  await page.locator('.mobile-work-title').click();
  await page.getByRole('button', { name: 'Close artwork information' }).click();
  await page.waitForFunction(() => window.document.activeElement?.classList.contains('mobile-work-title'));
  await page.screenshot({ path: '.browser-test-runtime/mobile-viewer-direct.png' });
  assert.deepEqual(errors, []);
  for (const mobile of [false, true]) {
    const context = await browser.newContext({ viewport: { width: mobile ? 390 : 1440, height: 900 }, hasTouch: mobile, isMobile: mobile, reducedMotion: 'reduce' });
    const visitor = await context.newPage(), requests = [];
    visitor.on('request', request => requests.push(request.url()));
    await visitor.route(`${origin}/__visitor__`, route => route.fulfill({ contentType: 'text/html', body: '<meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div>' }));
    await visitor.goto(`${origin}/__visitor__`);
    await visitor.evaluate(async document => {
      const refresh = (await import('/@react-refresh')).default;
      refresh.injectIntoGlobalHook(window); window.$RefreshReg$ = () => {}; window.$RefreshSig$ = () => type => type; window.__vite_plugin_react_preamble_installed__ = true;
      const React = (await import('/@id/react')).default, { createRoot } = (await import('/@id/react-dom/client')).default;
      await import('/src/index.css');
      const Preview = (await import('/src/profileDocument/components/ProfileDocumentV9Preview.jsx')).default;
      createRoot(window.document.getElementById('root')).render(React.createElement(Preview, { document }));
    }, document);
    await visitor.locator(mobile ? '.mobile-visitor' : '.visitor-grid-world').waitFor();
    assert.equal(requests.some(url => url.includes('/src/mobile/MobileEditor')), false);
    if (mobile) assert.equal(requests.some(url => url.includes('/ProfileDocumentV9Visitor.jsx')), false);
    else assert.equal(requests.some(url => url.includes('/src/mobile/MobilePresentation.jsx')), false);
    await context.close();
  }
  console.log('PASS direct Mobile editing, real Library drop, separate tools, username/title, shared undo, transforms, snap, works and visitor isolation');
} finally { await browser.close(); }
