import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import test from 'node:test';
import { chromium } from 'playwright-core';

const root = process.env.INSCAPE_SYSTEM_WORKFLOW_ROOT || 'http://127.0.0.1:5173';
const screenshots = process.env.INSCAPE_SYSTEM_WORKFLOW_SCREENSHOT_DIR;

test('Library resizes with inset scrolling, accessible controls, and retained state', async () => {
  const browser = await chromium.launch({ executablePath: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', headless: true });
  try {
    if (screenshots) await mkdir(screenshots, { recursive: true });
    const page = await browser.newPage();
    for (const width of [1440, 1024]) {
      await page.setViewportSize({ width, height: 900 });
      await page.goto(`${root}/development/owner/system-workflow`, { waitUntil: 'networkidle' });
      await page.evaluate(() => { window.__libraryDraftWrites = 0; addEventListener('inscape:review-storage-write', event => { if (event.detail.key.startsWith('inscape.system-workflow-draft.')) window.__libraryDraftWrites += 1; }); });
      const board = page.getByRole('article', { name: 'Display Module', exact: true });
      const grip = board.getByLabel(/Move Display Module:/);
      await grip.focus();
      const initialGrip = await grip.boundingBox();
      await page.mouse.move(initialGrip.x + 80, initialGrip.y + initialGrip.height / 2);
      await page.mouse.down();
      await page.mouse.move(650, initialGrip.y + initialGrip.height / 2, { steps: 8 });
      await page.mouse.up();
      const beforeLibrary = await board.boundingBox();
      const trigger = page.getByRole('button', { name: 'Library', exact: true });
      await trigger.click();
      const library = page.getByRole('region', { name: 'Library workspace' });
      await page.waitForFunction(() => document.querySelector('[aria-label="Library workspace"]')?.closest('[data-system-workflow-panel]')?.dataset.panelPhase === 'open');
      const original = await library.boundingBox();
      assert.deepEqual(await board.boundingBox(), beforeLibrary, 'opening Library never shifts or resizes Display');
      const handle = library.getByRole('button', { name: 'Resize Library', exact: true });
      await handle.press('Home');
      const minimum = (await library.boundingBox()).width;
      await handle.press('End');
      const maximum = (await library.boundingBox()).width;
      assert.ok(minimum > 0 && maximum > minimum && maximum <= width, 'keyboard endpoints define a nonempty, viewport-contained resize range');
      const edge = await handle.boundingBox();
      const shrink = (maximum - minimum) / 2;
      await page.mouse.move(edge.x + edge.width / 2, edge.y + 100);
      await page.mouse.down();
      await page.mouse.move(edge.x - shrink + edge.width / 2, edge.y + 100, { steps: 8 });
      await page.mouse.up();
      const smaller = await library.boundingBox();
      assert.ok(Math.abs(smaller.width - (maximum - shrink)) < 1, 'inside its limits, Library follows the dragged edge exactly');
      assert.deepEqual([smaller.x, smaller.y, smaller.height], [0, 0, original.height]);
      await handle.focus();
      await handle.press('Home');
      assert.equal((await library.boundingBox()).width, minimum);
      await handle.press('ArrowLeft');
      assert.equal((await library.boundingBox()).width, minimum, 'resize clamps at the lower endpoint');
      assert.deepEqual(await board.boundingBox(), beforeLibrary, 'resizing Library never shifts or resizes Display');
      await page.mouse.click(width - 30, 50);
      await page.waitForTimeout(350);
      assert.equal(await library.isVisible(), true, 'outside clicks keep Library open');
      const boardBounds = await board.boundingBox();
      await grip.focus();
      const gripBounds = await grip.boundingBox();
      await page.mouse.move(gripBounds.x + 80, gripBounds.y + gripBounds.height / 2);
      await page.mouse.down();
      await page.mouse.move(gripBounds.x + 125, gripBounds.y + gripBounds.height / 2 + 40, { steps: 6 });
      await page.mouse.up();
      await page.waitForTimeout(350);
      assert.equal(await library.isVisible(), true, 'Display Module interactions keep Library open');
      assert.notDeepEqual(await board.boundingBox(), boardBounds, 'the Display Module actually moves while Library stays open');
      await page.getByRole('button', { name: 'Tools', exact: true }).click();
      await page.getByRole('menuitem', { name: 'LAYERS', exact: true }).click();
      await page.locator('[data-shared-tool="layers"]').waitFor();
      assert.equal(await library.isVisible(), true, 'Layers can be used alongside Library');
      await page.getByRole('button', { name: 'Close Layers', exact: true }).click();
      const containment = await library.evaluate((node) => {
        const box = node.getBoundingClientRect();
        const dock = document.querySelector('.system-workflow__global-bar').getBoundingClientRect();
        const controls = [...node.querySelectorAll('.system-workflow__workspace-rail-controls > *')];
        return { gutter: dock.top - box.bottom, controlsFit: controls.every((control) => {
          const rect = control.getBoundingClientRect(); return rect.left >= box.left && rect.right <= box.right;
        }), bodyFits: node.scrollWidth <= node.clientWidth };
      });
      assert.deepEqual(containment, { gutter: 0, controlsFit: true, bodyFits: true });
      const scrolling = library.locator('.lattice-browser-results');
      await scrolling.evaluate((node) => { node.scrollTop = 150; });
      const safeSpace = await scrolling.evaluate((node) => {
        const rect = node.getBoundingClientRect();
        const panel = node.closest('.lattice-browser-panel').getBoundingClientRect();
        return [rect.top - panel.top, panel.bottom - rect.bottom];
      });
      assert.deepEqual(safeSpace, [10, 10], 'scroll clipping remains inset even between cards');
      if (screenshots) await page.screenshot({ path: resolve(screenshots, `library-scrolling-${width}.png`) });
      const scrollTop = await scrolling.evaluate((node) => node.scrollTop);
      await library.getByRole('button', { name: 'Close workspace' }).click();
      await page.waitForTimeout(400);
      await trigger.click();
      await page.waitForTimeout(400);
      assert.equal(await scrolling.evaluate((node) => node.scrollTop), scrollTop, 'reopening retains scroll position');
      await library.getByRole('button', { name: 'PORTFOLIO', exact: true }).click();
      await library.getByRole('button', { name: 'Close workspace' }).click();
      await page.waitForTimeout(400);
      await trigger.click();
      await page.waitForTimeout(400);
      assert.equal(await library.getByRole('button', { name: 'PORTFOLIO', exact: true }).getAttribute('aria-pressed'), 'true');
      await library.getByRole('button', { name: 'All Assets', exact: true }).click();
      await library.getByLabel('Search', { exact: true }).fill('ZEBRA');
      await page.waitForFunction(() => document.querySelectorAll('.system-workflow__library .lattice-browser-asset').length === 1);
      if (screenshots) await page.screenshot({ path: resolve(screenshots, `library-minimum-${width}.png`) });
      await library.getByRole('button', { name: 'Close workspace' }).click();
      await page.waitForTimeout(400);
      await trigger.click();
      await page.waitForTimeout(400);
      assert.equal((await library.boundingBox()).width, minimum, 'reopening retains resized width');
      assert.equal(await library.getByLabel('Search', { exact: true }).inputValue(), 'ZEBRA');
      await handle.press('ArrowRight');
      assert.ok((await library.boundingBox()).width > minimum, 'ArrowRight expands Library');
      await handle.press('End');
      assert.equal((await library.boundingBox()).width, maximum);
      await handle.press('ArrowRight');
      assert.equal((await library.boundingBox()).width, maximum, 'resize clamps at the upper endpoint');
      assert.equal(await page.evaluate(() => window.__libraryDraftWrites), 0, 'Library resizing and browsing never edits the draft');
      await library.getByLabel('Search', { exact: true }).fill('');
      if (screenshots) await page.screenshot({ path: resolve(screenshots, `library-expanded-${width}.png`) });
    }
    await page.setViewportSize({ width: 800, height: 900 });
    assert.ok((await page.getByRole('region', { name: 'Library workspace' }).boundingBox()).width <= 800);
  } finally { await browser.close(); }
});
