import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright-core';
import { mountTextToolsFixture } from './fixtures/text-tools-fixture.mjs';
const origin = process.env.INSCAPE_TEXT_ROOT || 'http://127.0.0.1:5173';

for (const width of [1440, 390]) test(`Text inspector preserves editing, document styles and Display connection at ${width}px`, { timeout: 90000 }, async () => {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width, height: 900 }, colorScheme: width === 1440 ? 'light' : 'dark' });
    page.setDefaultTimeout(10000);
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await mountTextToolsFixture(page, origin);
    const tools = page.locator('.text-tools-window'), body = page.getByRole('textbox', { name: 'Article text', exact: true });
    const scope = name => tools.getByRole('group', { name: 'Formatting target' }).getByRole('button', { name, exact: true });
    const section = name => tools.getByRole('tab', { name, exact: true });
    assert.equal(await tools.getByRole('combobox', { name: 'Follow Display', exact: true }).isVisible(), true);
    await body.fill('An illustrated article deserves careful typography.'); await body.press('Control+A');
    await tools.getByRole('button', { name: 'Bold', exact: true }).click();
    assert.equal(await body.locator('strong').innerText(), 'An illustrated article deserves careful typography.');
    await tools.locator('summary').filter({ hasText: 'Spacing & alignment' }).click();
    const tracking = tools.getByRole('spinbutton', { name: 'Selected text tracking', exact: true });
    await tracking.fill('.08'); await tracking.press('Enter');
    assert.equal(await body.locator('span').first().evaluate(n => n.style.letterSpacing), '0.08em');
    await section('Layout').click();
    assert.equal(await tools.getByRole('combobox', { name: 'Follow Display', exact: true }).isVisible(), true);
    assert.equal(await tools.getByRole('spinbutton', { name: 'Text column gap', exact: true }).count(), 0);
    await tools.getByRole('combobox', { name: 'Text columns', exact: true }).selectOption('2');
    await tools.getByRole('spinbutton', { name: 'Text column gap', exact: true }).fill('32');
    await tools.getByRole('combobox', { name: 'Text inner spacing', exact: true }).selectOption('custom');
    await tools.getByRole('spinbutton', { name: 'Text padding left', exact: true }).fill('10');
    await section('Appearance').click();
    await tools.getByRole('combobox', { name: 'Text background', exact: true }).selectOption('none');
    await section('Text').click(); await scope('Document').click();
    await tools.getByRole('spinbutton', { name: 'Text size', exact: true }).fill('18');
    await scope('Title').click();
    await tools.getByRole('spinbutton', { name: 'Title size', exact: true }).fill('36');
    const draft = await page.evaluate(() => window.savedDraft());
    assert.equal(draft.texts[0].article.appearance.fontSize, 18);
    assert.equal(draft.texts[0].article.appearance.titleFontSize, 36);
    assert.equal(draft.texts[0].article.appearance.columns, 2);
    assert.equal(draft.texts[0].article.appearance.columnGap, 32);
    assert.equal(draft.texts[0].article.appearance.padding.left, 10);
    assert.equal(draft.texts[0].article.appearance.background, null);
    await section('Layout').focus(); await page.keyboard.press('ArrowRight');
    assert.equal(await section('Appearance').getAttribute('aria-selected'), 'true');
    assert.equal(await section('Appearance').evaluate(n => document.activeElement === n), true);
    await section('Text').click(); await scope('Selection').click();
    await tools.locator('summary').filter({ hasText: 'Spacing & alignment' }).click();
    await tools.locator('.text-controls-body').evaluate(n => { n.scrollTop = 0; });
    await mkdir('.browser-test-runtime', { recursive: true });
    await tools.screenshot({ path: `.browser-test-runtime/text-inspector-${width}.png` });
    const overflow = await tools.locator('.text-controls-body').evaluate(n => n.scrollWidth - n.clientWidth);
    assert.ok(overflow <= 1, 'no horizontal clipping');
    // Changing tabs must not destroy the original Tiptap history or selection.
    assert.equal(await tools.getByRole('button', { name: 'Undo', exact: true }).isEnabled(), true);
    const follow = tools.getByRole('combobox', { name: 'Follow Display', exact: true });
    const target = await follow.locator('option').nth(1).getAttribute('value');
    await follow.selectOption(target); await tools.getByRole('button', { name: 'Link Text to Display', exact: true }).click();
    assert.equal((await page.evaluate(() => window.savedDraft())).texts[0].sceneLink.displayId, target);
    await tools.getByRole('button', { name: 'Unlink Text from Display', exact: true }).click();
    assert.equal((await page.evaluate(() => window.savedDraft())).texts[0].sceneLink, undefined);
    await mountTextToolsFixture(page, origin);
    await section('Text').click(); await scope('Document').click();
    assert.equal(await tools.getByRole('spinbutton', { name: 'Text size', exact: true }).inputValue(), '18');
    assert.equal(await body.locator('strong').innerText(), 'An illustrated article deserves careful typography.');
    assert.deepEqual(errors, []);
  } finally { await browser.close(); }
});
