import assert from 'node:assert/strict';
import test from 'node:test';
import { chromium } from 'playwright-core';
const origin = process.env.INSCAPE_TEXT_ROOT || 'http://127.0.0.1:5191';
test('Text tools, save recovery and drag into and out of Display', { timeout: 120000 }, async () => {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
    const errors = []; page.on('pageerror', error => { errors.push(error.message); console.error(error.stack); });
    await page.route('**/*', route => new URL(route.request().url()).origin === origin ? route.continue() : route.abort());
    await page.route(`${origin}/__text_transfer__`, route => route.fulfill({ contentType: 'text/html', body: '<div id="root"></div>' }));
    await page.goto(`${origin}/__text_transfer__`);
    await page.evaluate(async () => {
      const refresh = (await import('/@react-refresh')).default;
      refresh.injectIntoGlobalHook(window); window.$RefreshReg$ = () => {}; window.$RefreshSig$ = () => type => type; window.__vite_plugin_react_preamble_installed__ = true;
      const React = (await import('/@id/react')).default, { createRoot } = (await import('/@id/react-dom/client')).default;
      const Runtime = (await import('/src/public/ownerSystemWorkflow/OwnerSystemWorkflowRuntime.jsx')).default;
      const fixture = await import('/src/public/ownerSystemWorkflow/ownerSystemWorkflowDevelopmentFixture.js');
      const { createSystemWorkflowDraftStore, systemWorkflowDraftKey } = await import('/src/systemWorkflow/systemWorkflowDraftStore.js');
      const profile = fixture.OWNER_SYSTEM_WORKFLOW_REVIEW_PROFILE;
      const store = createSystemWorkflowDraftStore({ profileAddress: profile, storage: localStorage });
      const { addTextModule } = await import('/src/text/textSession.js'); addTextModule(store, profile);
      window.draftKey = systemWorkflowDraftKey(profile);
      window.readDraft = () => JSON.parse(localStorage.getItem(window.draftKey));
      await import('/src/inscapeTokens.css'); await import('/src/public/ownerSystemWorkflow/ownerSystemWorkflow.css'); await import('/src/lattice/rendering/latticeMenuSurface.css');
      createRoot(document.getElementById('root')).render(React.createElement(Runtime, { profileAddress: profile, reviewStorage: localStorage, reviewAssets: fixture.OWNER_SYSTEM_WORKFLOW_REVIEW_ASSETS,
        reviewCategories: [], reviewActivity: [], reviewDiscovery: [], reviewProfile: { name: 'Text transfer' } }));
    });
    const text = page.locator('[data-workbench-module="text"]'), output = text.locator('.text-window'), tools = text.locator('.text-tools-window');
    await tools.getByRole('textbox', { name: 'Article title', exact: true }).fill('Arrival');
    const body = output.getByRole('textbox', { name: 'Article text', exact: true });
    await body.fill('The landscape remembers.'); await page.keyboard.press('Control+A');
    await tools.getByRole('button', { name: 'Bold', exact: true }).click();
    assert.equal(await output.getByRole('toolbar').count(), 0);
    const writeBounds = await body.locator('p').boundingBox();
    await output.getByRole('button', { name: 'Read', exact: true }).click();
    const readBounds = await output.locator('article p').boundingBox();
    assert.ok(Math.abs(writeBounds.y - readBounds.y) < 1, 'Read does not move text');
    await output.getByRole('button', { name: 'Write', exact: true }).click();
    await tools.getByRole('combobox', { name: 'Text background', exact: true }).selectOption('colour');
    await tools.getByRole('checkbox', { name: 'Show text frame' }).check();
    assert.notEqual(await output.locator('.text-module-body').evaluate(node => getComputedStyle(node).backgroundColor), 'rgba(0, 0, 0, 0)');
    await tools.getByRole('combobox', { name: 'Text background', exact: true }).selectOption('none');
    await tools.getByRole('checkbox', { name: 'Show text frame' }).uncheck();
    // Simulate another writer updating unrelated saved data.
    await page.evaluate(() => { const draft = window.readDraft(); draft.identityPresentation.alias = 'Other tab'; localStorage.setItem(window.draftKey, JSON.stringify(draft)); });
    await body.fill('Unsaved but recoverable.');
    await tools.getByRole('button', { name: 'Retry local save', exact: true }).click();
    assert.equal(await tools.getByRole('alert').count(), 0);
    assert.equal(await page.evaluate(() => window.readDraft().identityPresentation.alias), 'Other tab');
    assert.equal(await page.evaluate(() => window.readDraft().texts[0].article.content.content[0].content[0].text), 'Unsaved but recoverable.');
    await body.fill('The landscape remembers.'); await page.keyboard.press('Control+A');
    if (!await body.locator('strong').count()) await tools.getByRole('button', { name: 'Bold', exact: true }).click();
    await tools.locator('.text-controls-body').evaluate(node => { node.scrollTop = 0; });
    await page.screenshot({ path: '.browser-test-runtime/text-tools-wide.png' });
    await tools.getByRole('button', { name: 'Close Text tools' }).click();
    const unlock = page.getByRole('button', { name: 'Unlock Display Module composition', exact: true }); if (await unlock.count()) await unlock.click({ force: true });
    const canvas = page.locator('[data-system-workflow-artboard]').first(), bounds = await canvas.boundingBox();
    const handle = output.getByRole('button', { name: 'Drag Text into Display' }); await output.hover();
    const from = await handle.boundingBox();
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2); await page.mouse.down();
    await page.mouse.move(bounds.x + bounds.width * .6, bounds.y + bounds.height * .55, { steps: 12 }); await page.mouse.up();
    await page.waitForTimeout(300);
    assert.equal(await text.count(), 0, 'attached text no longer has an independent window');
    const editor = canvas.getByRole('textbox', { name: 'Article text', exact: true }); await editor.waitFor();
    assert.equal(await editor.locator('strong').innerText(), 'The landscape remembers.');
    const externalTools = page.locator('.text-tools-window');
    assert.equal(await canvas.getByRole('toolbar').count(), 0);
    await externalTools.getByRole('textbox', { name: 'Article title', exact: true }).fill('Attached text');
    await externalTools.getByRole('button', { name: 'Close Text tools' }).click();
    await canvas.getByRole('button', { name: 'Select Attached text', exact: true }).dblclick();
    const outHandle = canvas.getByRole('button', { name: 'Drag Text out of Display' });
    const start = await outHandle.boundingBox();
    await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2); await page.mouse.down();
    await page.mouse.move(1580, 960, { steps: 8 }); await page.keyboard.press('Escape'); await page.mouse.up();
    assert.equal(await text.count(), 0, 'Escape cancels detachment, including the following pointer release');
    await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2); await page.mouse.down();
    await page.mouse.move(1580, 960, { steps: 12 }); await page.mouse.up();
    await page.screenshot({ path: '.browser-test-runtime/text-detach-debug.png' });
    await text.waitFor({ state: 'attached' });
    assert.equal(await text.locator('.text-editor-content strong').innerText(), 'The landscape remembers.');
    assert.equal(await page.evaluate(() => window.readDraft().grids.flatMap(grid => grid.placements).filter(item => item.kind === 'text').length), 0);
    await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(300);
    const toolBounds = await text.locator('.text-tools-window').boundingBox();
    assert.ok(toolBounds.x >= 0 && toolBounds.x + toolBounds.width <= 391);
    await page.screenshot({ path: '.browser-test-runtime/text-tools-narrow.png' });
    assert.deepEqual(errors, []);
  } finally { await browser.close(); }
});
