import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const origin = process.env.INSCAPE_TEXT_ROOT || 'http://127.0.0.1:5297';

test('reload restores local arrangement; failed Text survives editor disposal and blocks stale publication', { timeout: 120000 }, async () => {
  const shots = await mkdtemp(join(tmpdir(), 'inscape-workbench-recovery-'));
  console.log(`Screenshots: ${shots}`);
  const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    page.setDefaultTimeout(10000);
    const errors = []; page.on('pageerror', e => { errors.push(e.message); console.error(e.message); });
    await page.route('**/*', r => new URL(r.request().url()).origin === origin ? r.continue() : r.abort());
    await page.route(`${origin}/__recovery__`, r => r.fulfill({ contentType: 'text/html', body: '<div id="root"></div>' }));
    const mount = () => page.evaluate(async () => {
      const refresh = (await import('/@react-refresh')).default;
      refresh.injectIntoGlobalHook(window); window.$RefreshReg$ = () => {}; window.$RefreshSig$ = () => type => type; window.__vite_plugin_react_preamble_installed__ = true;
      const React = (await import('/@id/react')).default;
      const { createRoot } = (await import('/@id/react-dom/client')).default;
      const Runtime = (await import('/src/public/ownerSystemWorkflow/OwnerSystemWorkflowRuntime.jsx')).default;
      const { createSystemWorkflowDraftStore } = await import('/src/systemWorkflow/systemWorkflowDraftStore.js');
      const { addTextModule } = await import('/src/text/textSession.js');
      const { createDefaultWorkbenchPresentation, createTextPresentation } = await import('/src/profileDocument/domain/workbenchPresentation.js');
      const profileAddress = `0x${'1'.repeat(40)}`;
      const storage = { getItem: k => localStorage.getItem(k), setItem: (k, v) => {
        if (window.failDraft && k.startsWith('inscape.system-workflow-draft') || window.failLayout && k.startsWith('inscape:workbench:layout')) throw Error('full');
        localStorage.setItem(k, v);
      } };
      const store = createSystemWorkflowDraftStore({ profileAddress, storage });
      if (store.getRecordState().status === 'absent') {
        addTextModule(store, profileAddress);
        const draft = store.getDraft(); draft.texts[0].article.title = 'Arrival';
        draft.texts[0].article.content.content = [{ type: 'paragraph', content: [{ type: 'text', text: 'Remember this arrangement.' }] }];
        draft.workbench = createDefaultWorkbenchPresentation();
        draft.workbench.display.window = { left: 400, top: 100, width: 750, height: 421.875 };
        draft.workbench.texts = [{ ...createTextPresentation(draft.texts[0].id), window: { left: 40, top: 100, width: 300, height: 430 } }];
        store.commitCompletedOperation(draft, { expectedGeneration: store.getGeneration() });
      }
      window.readDraft = () => createSystemWorkflowDraftStore({ profileAddress, storage }).getDraft();
      window.readLayout = () => JSON.parse(localStorage.getItem(`inscape:workbench:layout:v1:${profileAddress}`));
      await import('/src/inscapeTokens.css'); await import('/src/public/ownerSystemWorkflow/ownerSystemWorkflow.css'); await import('/src/lattice/rendering/latticeMenuSurface.css');
      window.root = createRoot(document.getElementById('root'));
      window.root.render(React.createElement(Runtime, { profileAddress, reviewStorage: storage, reviewAssets: [], reviewCategories: [], reviewActivity: [], reviewDiscovery: [], reviewProfile: { name: 'Reload review' } }));
    });
    await page.goto(`${origin}/__recovery__`); await mount();
    const board = page.getByRole('article', { name: 'Display Module', exact: true });
    const text = page.locator('.text-window');
    await page.getByRole('button', { name: 'Close Text tools', exact: true }).click();
    await page.getByRole('button', { name: 'Read', exact: true }).focus(); await page.keyboard.press('Enter');
    const drag = async (handle, dx, dy) => {
      const b = await handle.boundingBox(); await page.mouse.move(b.x + 10, b.y + b.height / 2); await page.keyboard.down('Alt');
      await page.mouse.down(); await page.mouse.move(b.x + 10 + dx, b.y + b.height / 2 + dy, { steps: 5 }); await page.mouse.up(); await page.keyboard.up('Alt');
    };
    await drag(page.getByLabel('Move Text window', { exact: true }), 23, 41);
    await drag(page.getByRole('separator', { name: 'Resize Text window', exact: true }), 19, 37);
    await drag(page.getByLabel('Move Display Module: DISPLAY MODULE', { exact: true }), 43, 29);
    await page.getByRole('button', { name: 'Resize Display Module from se', exact: true }).focus(); await page.keyboard.press('Alt+ArrowLeft');
    const before = { text: await text.boundingBox(), board: await board.boundingBox(), draft: await page.evaluate(() => window.readDraft()) };
    await page.waitForFunction(() => window.readLayout()?.views?.['workbench:tools']?.layers === false);
    await page.screenshot({ path: join(shots, 'before-reload.png') });
    await page.reload(); await mount(); await text.waitFor();
    await page.waitForFunction(() => document.querySelector('.system-workflow__presentation-board')?.offsetWidth > 300);
    const near = (actual, expected) => { for (const key of ['x', 'y', 'width', 'height']) assert.ok(Math.abs(actual[key] - expected[key]) < 1, `${key}: ${actual[key]} != ${expected[key]}`); };
    near(await text.boundingBox(), before.text); near(await board.boundingBox(), before.board);
    assert.equal(await page.getByRole('button', { name: 'Close Text tools', exact: true }).count(), 0);
    assert.equal(await page.getByRole('button', { name: 'Write', exact: true }).count(), 1);
    assert.equal(await page.locator('[data-shared-tool="layers"]').count(), 0);
    assert.deepEqual(await page.evaluate(() => window.readDraft()), before.draft, 'restoring layout does not edit the canonical draft');
    await page.screenshot({ path: join(shots, 'after-reload.png') });
    await page.getByRole('button', { name: 'Close Arrival', exact: true }).focus(); await page.keyboard.press('Enter');
    await page.getByRole('button', { name: 'Minimize Display Module to shortcut', exact: true }).focus(); await page.keyboard.press('Enter');
    await page.reload(); await mount();
    await page.getByRole('button', { name: 'Arrival', exact: true }).waitFor();
    assert.equal(await text.count(), 0); assert.equal(await board.count(), 0);
    await page.getByRole('button', { name: 'Arrival', exact: true }).click();
    await page.getByRole('button', { name: /Open DISPLAY MODULE/ }).dblclick();
    near(await text.boundingBox(), before.text); near(await board.boundingBox(), before.board);
    // Saving can fail independently from closing the Display's embedded editor.
    await page.getByRole('button', { name: 'Tools', exact: true }).click();
    await page.getByRole('menuitem', { name: 'LAYERS', exact: true }).click();
    await page.getByRole('button', { name: 'Add text', exact: true }).click();
    const editor = page.getByRole('textbox', { name: 'Article text', exact: true });
    await editor.fill('Saved sentence.');
    await page.getByLabel('Article title', { exact: true }).fill('// ARRIVAL');
    assert.equal(await page.getByLabel('Title size', { exact: true }).inputValue(), '28');
    await page.getByLabel('Title size', { exact: true }).fill('64');
    assert.equal(await page.locator('.display-text-authoring .text-document-title').evaluate(node => getComputedStyle(node).fontSize), '64px');
    await page.getByLabel('Document font', { exact: true }).selectOption('literata');
    assert.match(await editor.evaluate(node => getComputedStyle(node).fontFamily), /Literata/);
    assert.match(await page.locator('.display-text-authoring .text-document-title').evaluate(node => getComputedStyle(node).fontFamily), /Literata/);
    assert.equal(await page.getByLabel('Document font', { exact: true }).inputValue(), 'literata');
    await page.evaluate(() => { window.failDraft = true; });
    await editor.fill('Keep this unsaved sentence.');
    await page.getByRole('button', { name: 'Retry local save', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Lock Display Module composition', exact: true }).focus(); await page.keyboard.press('Enter');
    assert.equal(await editor.count(), 0);
    await page.getByRole('button', { name: 'Preview', exact: true }).click();
    assert.equal(await page.locator('.visitor-grid-world').count(), 0);
    await page.getByRole('button', { name: 'Unlock Display Module composition', exact: true }).focus(); await page.keyboard.press('Enter');
    assert.equal(await editor.innerText(), 'Keep this unsaved sentence.');
    await page.evaluate(() => { window.failDraft = false; });
    await page.getByRole('button', { name: 'Retry local save', exact: true }).click();
    assert.equal(await page.locator('.system-workflow__recovery-notice').count(), 0);
    assert.ok(JSON.stringify(await page.evaluate(() => window.readDraft())).includes('Keep this unsaved sentence.'));
    await page.getByRole('button', { name: 'Finish editing Text', exact: true }).click();
    assert.equal(await page.locator('.display-text-content .text-document-title').evaluate(node => getComputedStyle(node).fontSize), '64px');
    await page.reload(); await mount();
    assert.equal(await page.locator('.display-text-content .text-document-title').evaluate(node => getComputedStyle(node).fontSize), '64px');
    await page.evaluate(() => { window.failLayout = true; });
    await drag(page.getByLabel('Move Text window', { exact: true }), 11, 7);
    await page.getByRole('button', { name: 'Save current layout', exact: true }).waitFor();
    await page.evaluate(() => { window.failLayout = false; });
    await page.getByRole('button', { name: 'Save current layout', exact: true }).click();
    assert.equal(await page.locator('.system-workflow__layout-notice').count(), 0);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: join(shots, 'narrow-restored.png') });
    assert.deepEqual(errors, []);
  } finally { await browser.close(); }
});
