export const createPhenomenaSlice = () => ({
  veinEnabled: true,
  veinIntensity: 0.35,
  veinReactionBoost: 0.75,
  veinSpeed: 1,
  veinScale: 18,
  veinWidth: 1,
  veinCore: 1.25,
  veinColorR: 255,
  veinColorG: 20,
  veinColorB: 77,
  veinSourceX: 0.5,
  veinSourceY: 0.58,

  weatherEnabled: true,
  weatherIntensity: 0.28,
  weatherScale: 2.2,
  weatherSpeed: 0.55,
  weatherColorR: 42,
  weatherColorG: 5,
  weatherColorB: 72,

  transfusionEnabled: true,
  transfusionIntensity: 0.78,
  transfusionScale: 3.4,
  transfusionBalance: 0.5,
  transfusionEdge: 0.38,

  tendrilAmount: 0,
  tendrilCount: 3,
  tendrilLength: 190,
  tendrilWidth: 1,
  tendrilWave: 0.85,
  tendrilWaveRepeats: 2.5,
  tendrilSpeed: 0.35,
  tendrilPulse: 0.1,
  tendrilAlignment: 0.82,
  tendrilTurnSpeed: 4,
  tendrilMovement: 0.8,

  shedSkinEnabled: true,
  shedSkinCount: 6,
  shedSkinSpacing: 4,
  shedSkinLifetime: 0.72,
  shedSkinOpacity: 0.58,
  shedSkinMotionThreshold: 0.035,
  shedSkinFullSpeed: 1.3,
  shedSkinFade: 1.45,
  shedSkinBackslide: 8,
  shedSkinDrift: 2,
  shedSkinExpansion: 0.018,
  shedSkinDissolve: 0.36,
  shedSkinColorMix: 0.58,
  shedSkinColorR: 112,
  shedSkinColorG: 24,
  shedSkinColorB: 164
});
