import { normalizeProfileAddress } from '../../library/config.js';
import { createErrorIdentity, createProfileIdentity, PROFILE_IDENTITY_STATUS } from '../domain/profileIdentity.js';
export class ProfileIdentityCache {
  constructor({ repository, maxConcurrent = 4, successTtlMs = 30 * 60_000, failureTtlMs = 60_000, now = Date.now } = {}) { if (!repository?.resolve) throw new TypeError('An identity repository is required'); this.repository = repository; this.maxConcurrent = Math.max(1, maxConcurrent); this.successTtlMs = successTtlMs; this.failureTtlMs = failureTtlMs; this.now = now; this.entries = new Map(); this.pending = new Map(); this.listeners = new Map(); this.queue = []; this.active = 0; }
  get(address) { const key = normalizeProfileAddress(address); if (!key) return null; const entry = this.entries.get(key); if (entry && entry.expiresAt > this.now()) return entry.identity; const identity = createProfileIdentity(key, { source: this.repository.source }); this.entries.set(key, { identity, expiresAt: Infinity }); return identity; }
  peek(address) { const identity = this.get(address); return identity?.status === PROFILE_IDENTITY_STATUS.RESOLVED ? identity : null; }
  subscribe(address, listener) { const key = normalizeProfileAddress(address); if (!key) return () => {}; const listeners = this.listeners.get(key) || new Set(); listeners.add(listener); this.listeners.set(key, listeners); return () => { listeners.delete(listener); if (!listeners.size) this.listeners.delete(key); }; }
  emit(key) { this.listeners.get(key)?.forEach((listener) => listener()); }
  resolve(address, options = {}) { const key = normalizeProfileAddress(address); if (!key) return Promise.reject(new TypeError('A valid address is required')); const cached = this.get(key); if (!options.force && cached?.status !== PROFILE_IDENTITY_STATUS.IDLE && cached?.status !== PROFILE_IDENTITY_STATUS.LOADING) return Promise.resolve(cached); if (this.pending.has(key)) return this.pending.get(key); this.entries.set(key, { identity: createProfileIdentity(key, { status: PROFILE_IDENTITY_STATUS.LOADING, source: this.repository.source }), expiresAt: Infinity }); this.emit(key); const promise = new Promise((resolve) => { this.queue.push({ key, options, resolve }); this.drain(); }); this.pending.set(key, promise); return promise; }
  drain() { while (this.active < this.maxConcurrent && this.queue.length) { const job = this.queue.shift(); this.active += 1; Promise.resolve(this.repository.resolve(job.key, job.options)).catch(() => createErrorIdentity(job.key, { source: this.repository.source })).then((identity) => { const successful = identity.status === PROFILE_IDENTITY_STATUS.RESOLVED; this.entries.set(job.key, { identity, expiresAt: this.now() + (successful ? this.successTtlMs : this.failureTtlMs) }); this.pending.delete(job.key); this.emit(job.key); job.resolve(identity); }).finally(() => { this.active -= 1; this.drain(); }); } }
  clear() { this.entries.clear(); this.pending.clear(); this.queue.length = 0; }
}
