const number = (path, label, min, max, step, options = {}) => Object.freeze({
  path, label, type: 'number', min, max, step, integer: options.integer === true
});

const boolean = (path, label) => Object.freeze({ path, label, type: 'boolean' });
const enumeration = (path, label, options) => Object.freeze({
  path,
  label,
  type: 'enum',
  options: Object.freeze(options),
  values: Object.freeze(options.map((option) => option.value))
});

export const RENDER_PARAMETER_DEFINITIONS = Object.freeze({
  characterId: enumeration(['actor', 'id'], 'Active Character', [
    { value: 'skull_reaper', label: 'Skull Reaper' },
    { value: 'abyssal_eye', label: 'Abyssal Eye' }
  ]),
  mutationMode: enumeration(['actor', 'geometry', 'mode'], 'Geometry', [
    { value: 'none', label: 'Original' },
    { value: 'mirrorX', label: 'Mirror Left / Right' },
    { value: 'mirrorY', label: 'Mirror Top / Bottom' },
    { value: 'quad', label: 'Four Way' }
  ]),
  mutationAxisX: number(['actor', 'geometry', 'axisX'], 'Vertical Axis', 0.05, 0.95, 0.001),
  mutationAxisY: number(['actor', 'geometry', 'axisY'], 'Horizontal Axis', 0.05, 0.95, 0.001),
  mutationSourceX: enumeration(['actor', 'geometry', 'sourceX'], 'X Source', [{ value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }]),
  mutationSourceY: enumeration(['actor', 'geometry', 'sourceY'], 'Y Source', [{ value: 'top', label: 'Top' }, { value: 'bottom', label: 'Bottom' }]),
  mutationRotation: number(['actor', 'geometry', 'rotation'], 'Source Rotation Offset', -180, 180, 1),
  mutationAutoRotate: boolean(['actor', 'geometry', 'autoRotate'], 'Auto Source Rotation'),
  mutationRotationDirection: enumeration(['actor', 'geometry', 'rotationDirection'], 'Rotation Direction', [{ value: 'clockwise', label: 'Clockwise' }, { value: 'counterclockwise', label: 'Counter-clockwise' }]),
  mutationRotationSpeed: number(['actor', 'geometry', 'rotationSpeed'], 'Rotation Speed (Deg / Sec)', 0, 90, 0.5),
  patternBottomScale: number(['actor', 'warp', 'patternBottomScale'], 'Pattern Bottom Scale', 0.5, 3, 0.1),
  patternTopScale: number(['actor', 'warp', 'patternTopScale'], 'Pattern Top Scale', 0.5, 3, 0.1),
  warpIntensity: number(['actor', 'warp', 'intensity'], 'Warp Intensity', 0, 100, 1),
  warpSpeed: number(['actor', 'warp', 'speed'], 'Warp Speed', 0, 5, 0.1),
  warpMode: enumeration(['actor', 'warp', 'mode'], 'Warp Behavior', [{ value: 'classic', label: 'Classic / Original' }, { value: 'organic', label: 'Organic / Layered' }]),
  warpOrganicRange: number(['actor', 'warp', 'organicRange'], 'Morph Range', 0, 3, 0.05),
  warpLayerDivergence: number(['actor', 'warp', 'layerDivergence'], 'Layer Divergence', 0, 1, 0.05),
  warpCursorInfluence: number(['actor', 'warp', 'cursorInfluence'], 'Cursor Influence', 0, 1, 0.05),
  warpCursorRadius: number(['actor', 'warp', 'cursorRadius'], 'Cursor Radius', 0.05, 0.5, 0.01),
  floatSpeed: number(['actor', 'motion', 'floatSpeed'], 'Float Speed', 0, 3, 0.1),
  floatAmpX: number(['actor', 'motion', 'floatAmpX'], 'Float Amp X (Sway)', 0, 400, 2),
  floatAmpY: number(['actor', 'motion', 'floatAmpY'], 'Float Amp Y (Rise)', 0, 400, 2),
  floatRotation: number(['actor', 'motion', 'floatRotation'], 'Wobble Rotation Osc', 0, 10, 0.1),
  flyMinScale: number(['actor', 'motion', 'flyMinScale'], 'Scale at Lowest Point', 0.5, 1.5, 0.05),
  flyMaxScale: number(['actor', 'motion', 'flyMaxScale'], 'Scale at Highest Peak', 0.3, 1.2, 0.05),
  flyHoverPause: number(['actor', 'motion', 'flyHoverPause'], 'Hover Pause Factor', 1, 5, 0.1),
  flyTiltBias: number(['actor', 'motion', 'flyTiltBias'], 'Tilt Bias (Degrees)', -20, 20, 0.5),
  eyelidTravel: number(['actor', 'eyes', 'eyelidTravel'], 'Eyelid Travel', 10, 100, 1),
  blinkInterval: number(['actor', 'eyes', 'blinkInterval'], 'Blink Interval', 1, 15, 0.5),
  blinkSpeed: number(['actor', 'eyes', 'blinkSpeed'], 'Blink Speed', 0.1, 5, 0.1),
  autoBlink: boolean(['actor', 'eyes', 'autoBlink'], 'Auto Blink'),
  eyelidManualProgress: number(['actor', 'eyes', 'eyelidManualProgress'], 'Manual Eyelid Openness', 0, 1, 0.05),
  pupilWander: number(['actor', 'eyes', 'pupilWander'], 'Pupil Drift (Wander)', 0, 3, 0.1),
  pupilSaccade: number(['actor', 'eyes', 'pupilSaccade'], 'Pupil Saccade Jitter', 0, 3, 0.1),
  pupilMouseInfluence: number(['actor', 'eyes', 'pupilMouseInfluence'], 'Pupil Mouse Influence', 0, 2, 0.1),
  auraOpacity: number(['actor', 'aura', 'opacity'], 'Aura Opacity', 0, 1, 0.05),
  auraScale: number(['actor', 'aura', 'scale'], 'Aura Scale', 1, 1.5, 0.01),
  auraBlur: number(['actor', 'aura', 'blur'], 'Aura Blur strength', 0, 50, 1),
  auraPulseSpeed: number(['actor', 'aura', 'pulseSpeed'], 'Aura Pulse Speed', 0, 5, 0.1),
  auraColorR: number(['actor', 'aura', 'color', 0], 'Red Channel', 0, 255, 1, { integer: true }),
  auraColorG: number(['actor', 'aura', 'color', 1], 'Green Channel', 0, 255, 1, { integer: true }),
  auraColorB: number(['actor', 'aura', 'color', 2], 'Blue Channel', 0, 255, 1, { integer: true }),
  cavernLightIntensity: number(['actor', 'aura', 'cavernLightIntensity'], 'Cavern Light Intensity', 0, 2, 0.05),
  searchlightActive: boolean(['actor', 'searchlight', 'enabled'], 'Enable Beams'),
  searchlightWidth: number(['actor', 'searchlight', 'width'], 'Beam Width', 0.1, 3, 0.05),
  searchlightLength: number(['actor', 'searchlight', 'length'], 'Beam Length', 0.2, 2, 0.05),
  searchlightRadius: number(['actor', 'searchlight', 'radius'], 'Emit Orbit Radius', 0, 300, 1),
  searchlightColorR: number(['actor', 'searchlight', 'color', 0], 'Beam Color: Red', 0, 255, 1, { integer: true }),
  searchlightColorG: number(['actor', 'searchlight', 'color', 1], 'Beam Color: Green', 0, 255, 1, { integer: true }),
  searchlightColorB: number(['actor', 'searchlight', 'color', 2], 'Beam Color: Blue', 0, 255, 1, { integer: true }),
  bgClippingMaskId: enumeration(['scene', 'background', 'backdropId'], 'Backdrop Color', [
    { value: 'beige', label: 'Beige Backdrop' },
    { value: 'black', label: 'Black Backdrop' },
    { value: 'darkblue', label: 'Dark Blue' },
    { value: 'darkgrey', label: 'Dark Grey' },
    { value: 'hotpink', label: 'Hot Pink' },
    { value: 'lightblue', label: 'Light Blue' },
    { value: 'lightgrey', label: 'Light Grey' },
    { value: 'orange', label: 'Orange' },
    { value: 'pastelpurple', label: 'Pastel Purple' },
    { value: 'purple', label: 'Purple' },
    { value: 'moonpurple', label: 'Moon Purple' }
  ]),
  bgPatternStyle: enumeration(['scene', 'background', 'patternStyle'], 'Pattern Style', [
    { value: 'bubble', label: 'Bubble Style' },
    { value: 'stone', label: 'Stone Style' },
    { value: 'digitalblob', label: 'Digital Blob' }
  ]),
  bgMountainId: enumeration(['scene', 'background', 'mountainFrontId'], 'Front Mountain', [
    { value: 1, label: 'Mountain 01' },
    { value: 2, label: 'Mountain 02' },
    { value: 3, label: 'Mountain 03' }
  ]),
  bgMountainBackId: enumeration(['scene', 'background', 'mountainBackId'], 'Back Mountain', [
    { value: 1, label: 'Mountain 01' },
    { value: 2, label: 'Mountain 02' },
    { value: 3, label: 'Mountain 03' }
  ]),
  bgScrollSpeed: number(['scene', 'background', 'scrollSpeed'], 'BG Scroll Speed', 0, 150, 5),
  bg2ParallaxSpeed: number(['scene', 'background', 'parallaxSpeed'], 'BG2 Parallax Factor', -5, 5, 0.1),
  bgPatternBottomScale: number(['scene', 'background', 'patternWarp', 'bottomScale'], 'BG Pattern Bottom Scale', 0.5, 3, 0.1),
  bgPatternTopScale: number(['scene', 'background', 'patternWarp', 'topScale'], 'BG Pattern Top Scale', 0.5, 3, 0.1),
  bgWarpIntensity: number(['scene', 'background', 'patternWarp', 'intensity'], 'BG Warp Intensity', 0, 100, 1),
  bgWarpSpeed: number(['scene', 'background', 'patternWarp', 'speed'], 'BG Warp Speed', 0, 5, 0.1),
  particleCount: number(['scene', 'atmosphere', 'particles', 'count'], 'Particle Count', 0, 300, 5, { integer: true }),
  particleSpeed: number(['scene', 'atmosphere', 'particles', 'speed'], 'Particle Speed', 0, 5, 0.1),
  particleWind: number(['scene', 'atmosphere', 'particles', 'wind'], 'Wind Drift', -20, 20, 1),
  particleSway: number(['scene', 'atmosphere', 'particles', 'sway'], 'Flutter Sway', 0, 5, 0.1),
  particleSize: number(['scene', 'atmosphere', 'particles', 'size'], 'Particle Size', 0.1, 3, 0.1),
  particleOpacity: number(['scene', 'atmosphere', 'particles', 'opacity'], 'Particle Opacity', 0, 1, 0.05),
  fogOpacity: number(['scene', 'atmosphere', 'fog', 'opacity'], 'Fog Opacity', 0, 1, 0.05),
  fogSpeed: number(['scene', 'atmosphere', 'fog', 'speed'], 'Fog Drift Speed', 0, 5, 0.1),
  fogColorR: number(['scene', 'atmosphere', 'fog', 'color', 0], 'Fog Color: Red', 0, 255, 1, { integer: true }),
  fogColorG: number(['scene', 'atmosphere', 'fog', 'color', 1], 'Fog Color: Green', 0, 255, 1, { integer: true }),
  fogColorB: number(['scene', 'atmosphere', 'fog', 'color', 2], 'Fog Color: Blue', 0, 255, 1, { integer: true }),
  fogSwaySpeed: number(['scene', 'atmosphere', 'fog', 'swaySpeed'], 'Fog Sway Speed', 0, 5, 0.1),
  fogSwayAmp: number(['scene', 'atmosphere', 'fog', 'swayAmplitude'], 'Fog Sway Amplitude', 0, 100, 1),
  veinEnabled: boolean(['phenomena', 'veins', 'enabled'], 'Enabled'),
  veinIntensity: number(['phenomena', 'veins', 'intensity'], 'Intensity', 0, 2, 0.01),
  veinReactionBoost: number(['phenomena', 'veins', 'reactionBoost'], 'Reaction Boost', 0, 2, 0.01),
  veinSpeed: number(['phenomena', 'veins', 'speed'], 'Speed', 0, 4, 0.01),
  veinScale: number(['phenomena', 'veins', 'scale'], 'Branch Scale', 1, 40, 0.1),
  veinWidth: number(['phenomena', 'veins', 'width'], 'Width', 0.2, 3, 0.01),
  veinCore: number(['phenomena', 'veins', 'core'], 'Core Light', 0, 3, 0.01),
  veinColorR: number(['phenomena', 'veins', 'color', 0], 'Color R', 0, 255, 1, { integer: true }),
  veinColorG: number(['phenomena', 'veins', 'color', 1], 'Color G', 0, 255, 1, { integer: true }),
  veinColorB: number(['phenomena', 'veins', 'color', 2], 'Color B', 0, 255, 1, { integer: true }),
  veinSourceX: number(['phenomena', 'veins', 'source', 0], 'Source X', 0, 1, 0.01),
  veinSourceY: number(['phenomena', 'veins', 'source', 1], 'Source Y', 0, 1, 0.01),
  weatherEnabled: boolean(['phenomena', 'weather', 'enabled'], 'Enabled'),
  weatherIntensity: number(['phenomena', 'weather', 'intensity'], 'Intensity', 0, 1.5, 0.01),
  weatherScale: number(['phenomena', 'weather', 'scale'], 'Scale', 0.5, 8, 0.01),
  weatherSpeed: number(['phenomena', 'weather', 'speed'], 'Speed', 0, 3, 0.01),
  weatherColorR: number(['phenomena', 'weather', 'color', 0], 'Color R', 0, 255, 1, { integer: true }),
  weatherColorG: number(['phenomena', 'weather', 'color', 1], 'Color G', 0, 255, 1, { integer: true }),
  weatherColorB: number(['phenomena', 'weather', 'color', 2], 'Color B', 0, 255, 1, { integer: true }),
  shedSkinEnabled: boolean(['phenomena', 'shedSkin', 'enabled'], 'Enabled'),
  shedSkinCount: number(['phenomena', 'shedSkin', 'count'], 'Shell Count', 0, 8, 1, { integer: true }),
  shedSkinSpacing: number(['phenomena', 'shedSkin', 'spacing'], 'Frame Spacing', 1, 16, 1, { integer: true }),
  shedSkinLifetime: number(['phenomena', 'shedSkin', 'lifetime'], 'Lifetime', 0.08, 3, 0.01),
  shedSkinOpacity: number(['phenomena', 'shedSkin', 'opacity'], 'Opacity', 0, 1, 0.01),
  shedSkinMotionThreshold: number(['phenomena', 'shedSkin', 'motionThreshold'], 'Motion Threshold', 0, 1, 0.01),
  shedSkinFullSpeed: number(['phenomena', 'shedSkin', 'fullSpeed'], 'Full Speed', 0.1, 5, 0.05),
  shedSkinFade: number(['phenomena', 'shedSkin', 'fade'], 'Age Fade', 0.2, 3, 0.05),
  shedSkinBackslide: number(['phenomena', 'shedSkin', 'backslide'], 'Backslide', 0, 80, 1),
  shedSkinDrift: number(['phenomena', 'shedSkin', 'drift'], 'Upward Drift', 0, 20, 0.5),
  shedSkinExpansion: number(['phenomena', 'shedSkin', 'expansion'], 'Shell Expansion', 0, 0.08, 0.001),
  shedSkinDissolve: number(['phenomena', 'shedSkin', 'dissolve'], 'Dissolve', 0, 1, 0.01),
  shedSkinColorMix: number(['phenomena', 'shedSkin', 'colorMix'], 'Color Mix', 0, 1, 0.01),
  shedSkinColorR: number(['phenomena', 'shedSkin', 'color', 0], 'Color R', 0, 255, 1, { integer: true }),
  shedSkinColorG: number(['phenomena', 'shedSkin', 'color', 1], 'Color G', 0, 255, 1, { integer: true }),
  shedSkinColorB: number(['phenomena', 'shedSkin', 'color', 2], 'Color B', 0, 255, 1, { integer: true }),
  aberrationAmount: number(['effects', 'chromaticAberration', 'amount'], 'RGB Split Amount', 0, 30, 0.5),
  aberrationSpeed: number(['effects', 'chromaticAberration', 'speed'], 'Aberration Speed', 0, 10, 0.1),
  aberrationGlitch: number(['effects', 'chromaticAberration', 'glitchBurstChance'], 'Glitch Burst Chance', 0, 5, 0.1),
  flickerIntensity: number(['effects', 'flicker', 'intensity'], 'Flicker Intensity', 0, 0.9, 0.05),
  flickerSpeed: number(['effects', 'flicker', 'speed'], 'Flicker Speed', 0, 5, 0.1),
  glitchShakeIntensity: number(['effects', 'glitch', 'screenShakeIntensity'], 'Screen Shake', 0, 30, 1),
  trailCount: number(['effects', 'spectralTrail', 'count'], 'Trail Count', 0, 3, 1, { integer: true }),
  trailSpacing: number(['effects', 'spectralTrail', 'spacing'], 'Frame Step Spacing', 2, 15, 1, { integer: true }),
  trailManualAlpha: number(['effects', 'spectralTrail', 'manualAlpha'], 'Manual Test Alpha', 0, 1, 0.05),
  trailGlitchInfluence: number(['effects', 'spectralTrail', 'glitchInfluence'], 'Glitch/Web3 Influence', 0, 1, 0.05),
  scanlineOpacity: number(['effects', 'screen', 'scanlineOpacity'], 'Scanline Density', 0, 1, 0.05),
  vignetteOpacity: number(['effects', 'screen', 'vignetteOpacity'], 'Vignette Intensity', 0, 1, 0.05),
  shockwaveStrength: number(['effects', 'shockwave', 'strength'], 'Shockwave Strength', 0, 2, 0.1),
  shockwaveThickness: number(['effects', 'shockwave', 'thickness'], 'Wavefront Thickness', 50, 300, 10),
  shockwaveDuration: number(['effects', 'shockwave', 'duration'], 'Ripple Expansion Time', 0.5, 4, 0.1),
  shockwavePulseCount: number(['effects', 'shockwave', 'pulseCount'], 'Cascading Ripple Count', 1, 5, 1, { integer: true })
});

export function getRenderParameterDefinition(key) {
  return RENDER_PARAMETER_DEFINITIONS[key] ?? null;
}
