import { useEffect, useState } from 'react';
import './navigationWallPrototype.css';
import './navigationWallPrototypeControls.css';

const ITEMS=[['01','FAVORITES'],['02','ART'],['03','KEEPERS'],['04','MUSIC'],['05','AUDIO'],['06','VIDEO'],['07','ANIMATION']];

function Range({label,value,min,max,step=1,suffix,onChange}){const update=(event)=>onChange(Math.max(min,Math.min(max,Number(event.target.value))));return <label className="wall-controls__range"><span>{label}</span><span className="wall-controls__number"><input aria-label={`${label} exact value`} type="number" min={min} max={max} step={step} value={value} onChange={update}/><i>{suffix}</i></span><input type="range" min={min} max={max} step={step} value={value} onChange={update}/></label>}

export default function NavigationWallPrototype(){
  const [open,setOpen]=useState(true);const [active,setActive]=useState('ART');const [width,setWidth]=useState(340);const [angle,setAngle]=useState(7);const [depth,setDepth]=useState(1200);const [speed,setSpeed]=useState(380);const [grid,setGrid]=useState(18);const [push,setPush]=useState(false);const [mobile,setMobile]=useState(false);const [controlsVisible,setControlsVisible]=useState(true);
  const applyPreset=(next)=>{setWidth(next.width);setAngle(next.angle);setDepth(next.depth);setSpeed(next.speed);setPush(next.push)};
  useEffect(()=>{const keydown=(event)=>{if(event.key==='Escape'){setOpen(false);return}const editing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(event.key.toLowerCase()==='n'&&!editing&&!event.metaKey&&!event.ctrlKey&&!event.altKey){event.preventDefault();setOpen((value)=>!value)}};window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown)},[]);
  const style={'--wall-width':`${width}px`,'--wall-angle':`${angle}deg`,'--wall-perspective':`${depth}px`,'--wall-speed':`${speed}ms`,'--wall-grid':grid/100};
  return <main className="wall-prototype" data-open={open||undefined} data-push={push||undefined} data-mobile={mobile||undefined} style={style}>
    <section className="wall-prototype__viewport" aria-label="Main grid viewport"><div className="wall-prototype__grid" aria-hidden="true"/><div className="wall-prototype__coordinates" aria-hidden="true"><span>Y 000</span><span>Y 080</span><span>Y 160</span><span>Y 240</span></div><header className="wall-prototype__masthead"><strong>OS_UNDERNEATH / NAVIGATION STUDY</strong><span>MAIN PLANE · STABLE</span></header><div className="wall-prototype__origin" aria-hidden="true"><i/><span>PRIMARY GRID</span></div><footer className="wall-prototype__status"><span>PROTOTYPE_02</span><i/><span>{mobile?'MOBILE DRAWER':push?'PUSH TEST':'CONNECTED OVERLAY'}</span></footer></section>
    <div className="wall-prototype__wall-space"><aside className="wall-prototype__wall" aria-hidden={!open}><div className="wall-prototype__wall-grid" aria-hidden="true"/><header><span>INDEX / 07</span><strong>NAVIGATION SEAM</strong><small>SAME GRID / ACCESS ANYWHERE</small></header><nav aria-label="Prototype navigation">{ITEMS.map(([code,label])=><button key={label} type="button" data-active={active===label||undefined} tabIndex={open?0:-1} onClick={()=>setActive(label)}><small>{code}</small><span>{label}</span><i aria-hidden="true">↗</i></button>)}</nav><footer><span>SEAM / FIXED</span><span>ACTIVE · {active}</span></footer></aside></div>
    <div className="wall-prototype__rail" aria-hidden="true"><span>NAV</span><i/><small>07</small></div>
    <button className="wall-prototype__toggle" type="button" aria-expanded={open} aria-keyshortcuts="N" aria-label={open?'Close navigation wall':'Open navigation wall'} onClick={()=>setOpen((value)=>!value)}>{open?'<':'>'}</button>
    <button className="wall-controls-toggle" type="button" aria-expanded={controlsVisible} onClick={()=>setControlsVisible((value)=>!value)}>[ {controlsVisible?'HIDE':'PARAMS'} ]</button>
    {controlsVisible&&<section className="wall-controls" aria-label="Prototype controls"><header><strong>SEAM PARAMETERS</strong><span>N / ESC</span></header><div className="wall-controls__presets"><button type="button" onClick={()=>applyPreset({width:300,angle:4,depth:1450,speed:300,push:false})}>CONNECTED</button><button type="button" onClick={()=>applyPreset({width:340,angle:7,depth:1200,speed:380,push:false})}>FOLDED</button><button type="button" onClick={()=>applyPreset({width:400,angle:14,depth:800,speed:560,push:false})}>DEEP</button></div><div className="wall-controls__ranges"><Range label="WIDTH" value={width} min={240} max={480} suffix="px" onChange={setWidth}/><Range label="ANGLE" value={angle} min={0} max={28} suffix="°" onChange={setAngle}/><Range label="DEPTH" value={depth} min={600} max={1800} step={25} suffix="px" onChange={setDepth}/><Range label="SPEED" value={speed} min={120} max={1200} step={20} suffix="ms" onChange={setSpeed}/><Range label="GRID" value={grid} min={4} max={42} suffix="%" onChange={setGrid}/></div><div className="wall-controls__switches"><button type="button" aria-pressed={!push} onClick={()=>setPush((value)=>!value)}>{push?'PUSH TEST':'CONNECTED OVERLAY'}</button><button type="button" aria-pressed={mobile} onClick={()=>setMobile((value)=>!value)}>{mobile?'MOBILE PREVIEW':'DESKTOP PREVIEW'}</button></div></section>}
  </main>
}
